Repository JohanChereau/wikicine-dawan, pull requests merged in 2024-06, with the labels that each got.

#31 header and homepage
  src/App.jsx
  src/components/ui/Header.jsx
  src/pages/HomePage.jsx
Labels: feature

#32 10 log in
  package-lock.json
  package.json
  src/App.jsx
  src/components/ui/BackgroundMesh.jsx
  src/components/ui/Checkbox.jsx
  src/components/ui/Form.jsx
  src/components/ui/Input.jsx
  src/components/ui/Label.jsx
  src/main.jsx
  src/pages/SignUpPage.jsx
  src/services/providers/auth-provider.jsx
  src/services/supabase/supabaseClient.js
Labels: user story

#33 29 film serie card
  jsconfig.json
  src/components/Badge.jsx
  src/components/Card.jsx
  src/pages/HomePage.jsx
Labels: feature

#34 6 log in
  package-lock.json
  package.json
  src/App.jsx
  src/components/Avatar.jsx
  src/components/ProtectedRoute.jsx
  src/components/ui/Button.jsx
  src/components/ui/Dropdown.jsx
  src/components/ui/Header.jsx
  src/components/ui/Select.jsx
  src/components/ui/Skeleton.jsx
  src/pages/HomePage.jsx
  src/pages/Root.jsx
  src/pages/SignInPage.jsx
  src/pages/SignOutPage.jsx
  src/pages/SignUpPage.jsx
  src/services/providers/auth-provider.jsx
  src/utils/string/capitalize.js
Labels: user story

#36 feat: log out page and bug fixes
  src/components/ui/Header.jsx
  src/pages/HomePage.jsx
  src/pages/SignInPage.jsx
  src/pages/SignOutPage.jsx
Labels: user story

#37 Movie page
  index.html
  src/App.jsx
  src/components/DescriptionMovie.jsx
  src/components/Tabs.jsx
  src/components/ui/Badge.jsx
  src/components/ui/Card.jsx
  src/components/ui/MovieHeader.jsx
  src/components/ui/Rating.jsx
  src/pages/MovieDetailsPage.jsx
Labels: user story

#38 1 search for a movie by text
  package-lock.json
  package.json
  src/App.jsx
  src/components/DescriptionMovie.jsx
  src/components/MoviesSearchResults.jsx
  src/components/MoviesSuggestions.jsx
  src/components/Tabs.jsx
  src/components/movie-tabs/MovieCast.jsx
  src/components/movie-tabs/MovieTabs.jsx
  src/components/ui/BackgroundMesh.jsx
  src/components/ui/Badge.jsx
  src/components/ui/Button.jsx
  src/components/ui/Card.jsx
  src/components/ui/Carousel.jsx
  src/components/ui/Footer.jsx
  src/components/ui/Header.jsx
  src/components/ui/MovieDetailsContent.jsx
  src/components/ui/MovieHeader.jsx
  src/components/ui/MoviePreviewCard.jsx
  src/components/ui/MovieRating.jsx
  src/components/ui/MoviesCarousel.jsx
  src/components/ui/Rating.jsx
  src/components/ui/Tabs.jsx
  src/hooks/use-debounce.js
  src/hooks/use-movies.js
  src/main.jsx
  src/pages/ErrorPage.jsx
  src/pages/HomePage.jsx
  src/pages/MovieDetailsPage.jsx
  src/pages/Root.jsx
  src/services/api/actions/movieCredits.js
  src/services/api/actions/movieDetails.js
  src/services/api/actions/movieRecommendations.js
  src/services/api/actions/popularMovies.js
  src/services/api/actions/searchMovies.js
  src/services/api/actions/trendingMovies.js
  src/services/api/fetchUtils.js
  src/services/api/index.js
  src/utils/string/truncate.js
  tailwind.config.js
Labels: user story

#39 4 view comments on a movies details page
  package-lock.json
  package.json
  src/components/Avatar.jsx
  src/components/layout/Footer.jsx
  src/components/layout/Header.jsx
  src/components/movie-tabs/MovieCastTab.jsx
  src/components/movie-tabs/MovieReviewsTab.jsx
  src/components/movie-tabs/MovieTabs.jsx
  src/components/ui/MovieRating.jsx
  src/components/ui/RoleBadge.jsx
  src/components/ui/Tooltip.jsx
  src/hooks/use-reviews.js
  src/pages/Root.jsx
  src/utils/icons/Badges.js
Labels: user story

#40 8 write a comment about a movie
  package-lock.json
  package.json
  src/components/modals/MovieReviewModal.jsx
  src/components/movie-tabs/MovieCastTab.jsx
  src/components/movie-tabs/MovieReviewsTab.jsx
  src/components/movie-tabs/MovieTabs.jsx
  src/components/ui/Dialog.jsx
  src/components/ui/MovieComment.jsx
  src/components/ui/MovieDetailsContent.jsx
  src/components/ui/MovieHeader.jsx
  src/components/ui/Slider.jsx
  src/components/ui/TextArea.jsx
  src/hooks/use-reviews.js
  src/hooks/use-userProfile.js
  src/pages/MovieDetailsPage.jsx
Labels: user story

#58 fix: corrected full-screen display of movie cards in mobile version.
  src/components/MoviesSearchResults.jsx
Labels: bug

#60 fix: comments now correctly support markdown.
  src/components/ui/MovieComment.jsx
  src/components/users/UserProfileReview.jsx
  src/index.css
  src/pages/CreateWikiPage.jsx
Labels: bug

#62 61 bug add review button displayed according to role
  src/components/modals/MovieReviewModal.jsx
  src/components/movie-tabs/MovieReviewsTab.jsx
  src/components/movie-tabs/MovieTabs.jsx
Labels: bug
